### PR TITLE
make a nonsolid wall solid

### PR DESCRIPTION
**Pull request by sweet235**

### CODE REVIEW

**Comment by sweet235** [comment]
This was approved on IRC.

**Comment by mjstahlberg** [comment]
Is this the wall in your video? I wonder why this wasn't noticed before as this should be a common place to wallclimb. In any case I'm fine with the fix.

**Comment by sweet235** [comment]
> Is this the wall in your video?

Yes.

> I wonder why this wasn't noticed before as this should be a common place to wallclimb.

Because our q3map2 had a bug.

**Comment by illwieckz** [comment]
For the memories, here was the nonsolid wall (painted in blue):

unvanquished_2024-10-25_183011_000

**Comment by sweet235** [comment]
This is a rather common mistake to make when mapping, this happened in a few of our maps. One method to spot these surfaces in Netradiant is to search for `nonsolid` in the shader files, and temporarily use this line in the affected shaders:

```
	qer_editorImage textures/shared_colors_src/red_d
```

**Pull request merged**
